In [2]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import pandas as pd

#Define the database credentials
username = "consultants"
password = quote_plus("WelcomeItc@2022")
host = "18.170.23.150"
port = "5432"
database = "testdb"

#Construct the database connection URL
connection_string = f"postgresql://{username}:{password}@{host}:{port}/{database}"

In [3]:
try:    
    #Create the SQLAlchemy engine
    db_conn = create_engine(connection_string)
    print(f"Connection to the {host} for user {username} created successful.")
except Exception as e:
    print(f"Connection could not be made due to the following error: \n", e)

Connection to the 18.170.23.150 for user consultants created successful.

# Uploading Full Data on PostgreSQL cloud

In [12]:
df_full_load = pd.read_csv("./data/full_load.csv")
print("Shape of the DataFrame:", df_full_load.shape)
df_full_load.head()

Shape of the DataFrame: (4500, 8)

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22

In [13]:
df_full_load.to_sql(
    name='om_emp_records',
    con=db_conn,
    if_exists='replace',  # Options: 'fail', 'replace', 'append'
    index=False,          # Do not write DataFrame index as a column
    method='multi'       # Use multi-row insert for better performance
)

# Close the connection
db_conn.dispose()

# Appending Another CSV File To PostgreSQL For Incremental Load

In [4]:
df_inc_load = pd.read_csv("./data/inc_load.csv")
print("Shape of the DataFrame:", df_inc_load.shape)
df_inc_load.head()

Shape of the DataFrame: (1000, 8)

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date
0,4501,Ethan Hernandez,57,France,Finance,Assistant,72163.37,2024-01-30
1,4502,Sophia Brown,40,USA,Support,Executive,68032.64,2020-11-11
2,4503,Ava Taylor,31,Australia,Finance,Consultant,87596.22,2021-02-27
3,4504,Mia Brown,43,Brazil,Engineering,Consultant,143694.59,2020-02-08
4,4505,Lucas Thomas,23,India,Support,Analyst,109511.20,2024-08-21

In [6]:
df_inc_load.to_sql(
    name='om_emp_records',
    con=db_conn,
    if_exists='append',  # Options: 'fail', 'replace', 'append'
    index=False,          # Do not write DataFrame index as a column
    method='multi'       # Use multi-row insert for better performance
)

# Close the connection
db_conn.dispose()